services:
  fastapi:
    build: .
    container_name: fastapi_postos
    ports:
      - "11000:11000"
    command: uv run gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:11000 --workers 2
  minio:
    image: minio/minio:latest
    container_name: minio_postos
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
  postgres:
    image: postgres:latest
    container_name: postgres_postos
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: csvdb
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data