[project]
name = "intepretadordadospostos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "fastapi[standard]==0.115.11",
    "gunicorn==23.0.0",
    "python-dotenv==1.0.0",
    "streamlit==1.22.0",
    "llama-index-embeddings-azure-openai==0.3.1",
    "llama-index==0.12.25",
    "minio==7.2.15",
    "prefect==3.2.14",
    "psycopg2-binary==2.9.10",
    "llama-index-llms-ollama==0.5.3",
    "llama-index-embeddings-huggingface==0.5.2",
    "openai==1.83.0",
    "openpyxl==3.1.5"
]
